"use strict";

const stories = [
  // EPIC-001
  {
    id: "US-001",
    title: "Register with email and password",
    epicId: "EPIC-001",
    status: "done",
    priority: "high",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-01",
    dueDate: "2026-05-07",
  },
  {
    id: "US-002",
    title: "Log in with Google or Facebook",
    epicId: "EPIC-001",
    status: "done",
    priority: "high",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-05",
    dueDate: "2026-05-10",
  },
  {
    id: "US-003",
    title: "Manage user profile and avatar",
    epicId: "EPIC-001",
    status: "active",
    priority: "medium",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-15",
    dueDate: "2026-05-21",
  },
  {
    id: "US-004",
    title: "Reset forgotten password via email",
    epicId: "EPIC-001",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-18",
    dueDate: "2026-05-22",
  },
  // EPIC-002
  {
    id: "US-005",
    title: "Create and publish a product listing",
    epicId: "EPIC-002",
    status: "done",
    priority: "high",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-03",
    dueDate: "2026-05-12",
  },
  {
    id: "US-006",
    title: "Upload and reorder product images",
    epicId: "EPIC-002",
    status: "done",
    priority: "high",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-06",
    dueDate: "2026-05-13",
  },
  {
    id: "US-007",
    title: "Browse products by category",
    epicId: "EPIC-002",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-15",
    dueDate: "2026-05-23",
  },
  {
    id: "US-008",
    title: "View product detail page",
    epicId: "EPIC-002",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-17",
    dueDate: "2026-05-25",
  },
  // EPIC-003
  {
    id: "US-009",
    title: "Add product to shopping cart",
    epicId: "EPIC-003",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-20",
    dueDate: "2026-05-26",
  },
  {
    id: "US-010",
    title: "Edit and remove cart items",
    epicId: "EPIC-003",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-21",
    dueDate: "2026-05-27",
  },
  {
    id: "US-011",
    title: "Complete checkout as a guest",
    epicId: "EPIC-003",
    status: "draft",
    priority: "medium",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-01",
    dueDate: "2026-06-07",
  },
  {
    id: "US-012",
    title: "Receive order confirmation email",
    epicId: "EPIC-003",
    status: "draft",
    priority: "medium",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-03",
    dueDate: "2026-06-08",
  },
  // EPIC-004
  {
    id: "US-013",
    title: "Pay with credit or debit card",
    epicId: "EPIC-004",
    status: "draft",
    priority: "high",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-01",
    dueDate: "2026-06-10",
  },
  {
    id: "US-014",
    title: "Pay via PayPal redirect",
    epicId: "EPIC-004",
    status: "draft",
    priority: "medium",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-04",
    dueDate: "2026-06-12",
  },
  {
    id: "US-015",
    title: "Request a refund for an order",
    epicId: "EPIC-004",
    status: "draft",
    priority: "medium",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-08",
    dueDate: "2026-06-14",
  },
  // EPIC-005
  {
    id: "US-016",
    title: "Register as a seller",
    epicId: "EPIC-005",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-002",
    startDate: "2026-05-19",
    dueDate: "2026-05-28",
  },
  {
    id: "US-017",
    title: "View seller revenue dashboard",
    epicId: "EPIC-005",
    status: "active",
    priority: "high",
    sprintId: "SPR-002",
    releaseId: "REL-002",
    startDate: "2026-05-22",
    dueDate: "2026-05-28",
  },
  {
    id: "US-018",
    title: "Manage inventory and stock levels",
    epicId: "EPIC-005",
    status: "draft",
    priority: "medium",
    releaseId: "REL-002",
    startDate: "2026-07-01",
    dueDate: "2026-07-10",
  },
  // EPIC-006
  {
    id: "US-019",
    title: "Search products with full-text",
    epicId: "EPIC-006",
    status: "draft",
    priority: "high",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-01",
    dueDate: "2026-06-12",
  },
  {
    id: "US-020",
    title: "Filter search results by facets",
    epicId: "EPIC-006",
    status: "draft",
    priority: "high",
    sprintId: "SPR-003",
    releaseId: "REL-002",
    startDate: "2026-06-08",
    dueDate: "2026-06-20",
  },
  {
    id: "US-021",
    title: "See autocomplete suggestions",
    epicId: "EPIC-006",
    status: "draft",
    priority: "medium",
    releaseId: "REL-002",
    startDate: "2026-07-01",
    dueDate: "2026-07-10",
  },
  // EPIC-007
  {
    id: "US-022",
    title: "Write a review for a purchased item",
    epicId: "EPIC-007",
    status: "draft",
    priority: "medium",
    releaseId: "REL-002",
    startDate: "2026-07-01",
    dueDate: "2026-07-14",
  },
  {
    id: "US-023",
    title: "Rate a product with stars",
    epicId: "EPIC-007",
    status: "draft",
    priority: "medium",
    releaseId: "REL-002",
    startDate: "2026-07-01",
    dueDate: "2026-07-10",
  },
  {
    id: "US-024",
    title: "Moderate and approve reviews",
    epicId: "EPIC-007",
    status: "draft",
    priority: "low",
    releaseId: "REL-002",
    startDate: "2026-07-14",
    dueDate: "2026-07-24",
  },
  // EPIC-008
  {
    id: "US-025",
    title: "Track order status and shipment",
    epicId: "EPIC-008",
    status: "draft",
    priority: "high",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-05",
    dueDate: "2026-06-14",
  },
  {
    id: "US-026",
    title: "Cancel an order within 1 hour",
    epicId: "EPIC-008",
    status: "draft",
    priority: "medium",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-08",
    dueDate: "2026-06-14",
  },
  {
    id: "US-027",
    title: "Submit a return request",
    epicId: "EPIC-008",
    status: "draft",
    priority: "medium",
    releaseId: "REL-002",
    startDate: "2026-07-01",
    dueDate: "2026-07-14",
  },
];

const storyBodies = {
  "US-001": `## Description\n\nAs a buyer or seller, I can create an account using my email address and a password so that I can access the marketplace.\n\n## Acceptance Criteria\n\n- [ ] Form requires email (validated), password (min 8 chars, 1 uppercase, 1 digit)\n- [ ] Duplicate email shows inline error\n- [ ] Verification email sent; account inactive until confirmed\n- [ ] Successful verification redirects to the dashboard\n\n## Notes\n\nBcrypt password hashing with cost factor 12.\n`,
  "US-002": `## Description\n\nAs a user, I can log in with my existing Google or Facebook account so that I don't need to remember another password.\n\n## Acceptance Criteria\n\n- [ ] "Continue with Google" button triggers OAuth2 PKCE flow\n- [ ] "Continue with Facebook" button triggers OAuth2 flow\n- [ ] New users are auto-registered on first OAuth login\n- [ ] Profile photo imported from OAuth provider\n\n## Notes\n\nStore provider user ID and access token for API calls.\n`,
  "US-003": `## Description\n\nAs a logged-in user, I can update my display name, avatar, bio, and contact email so that my profile is current.\n\n## Acceptance Criteria\n\n- [ ] Avatar upload accepts JPEG/PNG up to 5 MB\n- [ ] Display name must be 2–50 characters\n- [ ] Changes are saved immediately and reflected in the header\n\n## Notes\n\nAvatar processed to 256×256 px and stored in S3.\n`,
  "US-004": `## Description\n\nAs a user who forgot their password, I can receive a reset link by email so that I can regain access to my account.\n\n## Acceptance Criteria\n\n- [ ] Request page accepts email; always shows success message to prevent enumeration\n- [ ] Reset token expires in 1 hour\n- [ ] Token is single-use; invalidated after use\n- [ ] New password must meet complexity requirements\n\n## Notes\n\nTokens stored as HMAC-SHA256 hash in DB.\n`,
  "US-005": `## Description\n\nAs a registered seller, I can create a new product listing with title, description, price, category, and stock so that buyers can find and purchase it.\n\n## Acceptance Criteria\n\n- [ ] All required fields validated before publish\n- [ ] Listing enters "pending review" state until approved\n- [ ] Seller sees listing in their dashboard immediately\n\n## Notes\n\nApproval can be auto-approved for trusted sellers.\n`,
  "US-006": `## Description\n\nAs a seller, I can upload up to 8 images per listing and drag-to-reorder them so that the primary image is shown first.\n\n## Acceptance Criteria\n\n- [ ] Accepts JPEG, PNG, WebP up to 10 MB each\n- [ ] Images resized to max 1600 px on longest side\n- [ ] Drag handle visible on mobile\n\n## Notes\n\nUse presigned S3 upload URLs to avoid routing large files through the API.\n`,
  "US-007": `## Description\n\nAs a buyer, I can browse a category tree and see paginated product cards so that I can discover items relevant to me.\n\n## Acceptance Criteria\n\n- [ ] Top-level categories shown in nav; subcategories on hover/tap\n- [ ] Page shows 24 products with infinite scroll\n- [ ] Sort by: relevance, price asc/desc, newest\n\n## Notes\n\nCategory data cached in Redis for 10 minutes.\n`,
  "US-008": `## Description\n\nAs a buyer, I can view a product detail page with images, description, specifications, seller info, and related products.\n\n## Acceptance Criteria\n\n- [ ] Image gallery with zoom on hover\n- [ ] Add-to-cart button disabled when out of stock\n- [ ] Related products section shows 4 items from same category\n\n## Notes\n\nPage rendered SSR for SEO.\n`,
  "US-009": `## Description\n\nAs a buyer, I can add a product to my shopping cart from the detail page or search results.\n\n## Acceptance Criteria\n\n- [ ] Cart icon updates count immediately\n- [ ] Adding same item increments quantity\n- [ ] Stock check performed on add; out-of-stock items show error\n\n## Notes\n\nCart stored in Redis (authenticated users) or localStorage (guests).\n`,
  "US-010": `## Description\n\nAs a buyer, I can view my cart, update quantities, and remove items before checking out.\n\n## Acceptance Criteria\n\n- [ ] Quantity field validates against current stock\n- [ ] Remove button removes item immediately\n- [ ] Subtotal, tax estimate, and shipping estimate shown\n\n## Notes\n\nCart synced to server on every mutation.\n`,
  "US-011": `## Description\n\nAs a visitor without an account, I can complete checkout by providing my email, shipping address, and payment details.\n\n## Acceptance Criteria\n\n- [ ] Guest email captured for order confirmation\n- [ ] No account creation required\n- [ ] Post-purchase prompt to create account\n\n## Notes\n\nGuest orders linked to email, upgradeable to account later.\n`,
  "US-012": `## Description\n\nAs a buyer, I receive a confirmation email immediately after placing an order, with a summary and tracking link.\n\n## Acceptance Criteria\n\n- [ ] Email sent within 30 seconds of order creation\n- [ ] Email contains: order ID, item list, total, shipping address, and tracking link\n- [ ] Resend confirmation button available in order detail page\n\n## Notes\n\nSend via SendGrid transactional template.\n`,
  "US-013": `## Description\n\nAs a buyer, I can pay for my order using a credit or debit card via a secure hosted payment form.\n\n## Acceptance Criteria\n\n- [ ] Stripe Elements used — card data never touches our servers\n- [ ] 3DS2 challenge shown when required\n- [ ] Failed payment shows actionable error message\n\n## Notes\n\nCapture payment at order fulfillment, not at checkout (authorize-only).\n`,
  "US-014": `## Description\n\nAs a buyer, I can choose PayPal at checkout and complete payment on the PayPal site, then return to the order confirmation.\n\n## Acceptance Criteria\n\n- [ ] PayPal Smart Button rendered in checkout\n- [ ] Order created on our side only after PayPal capture succeeds\n- [ ] Webhook handles async payment events\n\n## Notes\n\nUse PayPal Orders v2 API.\n`,
  "US-015": `## Description\n\nAs a buyer, I can request a refund for an order within 30 days, and the refund is processed back to my original payment method.\n\n## Acceptance Criteria\n\n- [ ] Refund request triggers seller notification\n- [ ] Seller has 48 hours to approve or dispute\n- [ ] Auto-approved refunds processed within 5 business days\n\n## Notes\n\nStripe Refund API; PayPal refunds via PayPal Orders API.\n`,
  "US-016": `## Description\n\nAs a user, I can apply to become a seller by completing a business profile and connecting a bank account.\n\n## Acceptance Criteria\n\n- [ ] Onboarding wizard: business name, type, tax ID, bank account\n- [ ] KYC verification via Stripe Identity\n- [ ] Seller account activated within 1 business day\n\n## Notes\n\nStripe Connect Express accounts.\n`,
  "US-017": `## Description\n\nAs a seller, I can view my dashboard showing total revenue, recent orders, and my top-performing products.\n\n## Acceptance Criteria\n\n- [ ] Revenue chart shows last 30 days by default; adjustable to 7 / 90 days\n- [ ] Orders table with status and customer name\n- [ ] Top products by revenue and units sold\n\n## Notes\n\nData aggregated nightly via background job.\n`,
  "US-018": `## Description\n\nAs a seller, I can view and update stock levels for all my listings and be alerted when stock falls below a threshold.\n\n## Acceptance Criteria\n\n- [ ] Bulk stock update via CSV import\n- [ ] Low-stock alert email when stock ≤ 5 units\n- [ ] Listings automatically paused at 0 stock\n\n## Notes\n\nAlerts sent via SendGrid; re-listed automatically when stock updated > 0.\n`,
  "US-019": `## Description\n\nAs a buyer, I can type a query in the search bar and see relevant products from across the marketplace.\n\n## Acceptance Criteria\n\n- [ ] Results returned within 300 ms for 95th percentile\n- [ ] Fuzzy matching handles minor typos\n- [ ] Results ranked by relevance (BM25 + seller rating boost)\n\n## Notes\n\nElasticsearch index rebuilt nightly; real-time updates via CDC.\n`,
  "US-020": `## Description\n\nAs a buyer, I can refine search results using filters for category, price range, star rating, and availability.\n\n## Acceptance Criteria\n\n- [ ] Facet counts update dynamically as filters are applied\n- [ ] Price slider with min/max input fields\n- [ ] Selected filters shown as removable chips\n\n## Notes\n\nAggregations computed by Elasticsearch; cache frequently used filter combinations.\n`,
  "US-021": `## Description\n\nAs a buyer, I see autocomplete suggestions in the search bar after typing 2 or more characters.\n\n## Acceptance Criteria\n\n- [ ] Suggestions include product names, category names, and trending queries\n- [ ] Results debounced at 150 ms\n- [ ] Keyboard navigable; selected suggestion fills the search bar\n\n## Notes\n\nDedicated autocomplete index with edge-ngram tokenizer.\n`,
  "US-022": `## Description\n\nAs a buyer who completed a purchase, I can write a text review for the product.\n\n## Acceptance Criteria\n\n- [ ] Review form unlocked only after order marked "delivered"\n- [ ] Title (max 80 chars) and body (max 2 000 chars)\n- [ ] One review per buyer per product\n\n## Notes\n\nStore as Markdown; render with DOMPurify.\n`,
  "US-023": `## Description\n\nAs a buyer, I can rate a product 1–5 stars alongside or independently of a written review.\n\n## Acceptance Criteria\n\n- [ ] Star widget interactive with hover state\n- [ ] Rating saved immediately on click\n- [ ] Aggregate rating recalculated and visible within 5 seconds\n\n## Notes\n\nAverage stored denormalized on Product for fast reads.\n`,
  "US-024": `## Description\n\nAs an admin, I can see a moderation queue of flagged reviews and approve or reject them.\n\n## Acceptance Criteria\n\n- [ ] Reviews auto-flagged by profanity filter\n- [ ] Admin sees review text, rating, product, and reviewer\n- [ ] Bulk approve/reject with optional note to reviewer\n\n## Notes\n\nPerspective API for content scoring.\n`,
  "US-025": `## Description\n\nAs a buyer, I can view the current status and tracking information for each of my orders.\n\n## Acceptance Criteria\n\n- [ ] Status timeline: placed → processing → shipped → delivered\n- [ ] Carrier tracking number linked to carrier tracking page\n- [ ] Push notification and email on each status change\n\n## Notes\n\nShipStation webhook updates order status in real time.\n`,
  "US-026": `## Description\n\nAs a buyer, I can cancel an order within 1 hour of placing it, provided it has not yet shipped.\n\n## Acceptance Criteria\n\n- [ ] Cancel button visible on order detail for eligible orders\n- [ ] Payment voided immediately for auth-only captures\n- [ ] Cancellation confirmation email sent\n\n## Notes\n\nCancellation window enforced server-side.\n`,
  "US-027": `## Description\n\nAs a buyer, I can submit a return request within 30 days of delivery and receive a prepaid return label.\n\n## Acceptance Criteria\n\n- [ ] Return reasons: wrong item, damaged, changed mind, other\n- [ ] Seller receives return request notification\n- [ ] Prepaid label generated via ShipStation API\n\n## Notes\n\nReturn window configurable per seller.\n`,
};

/** @param {Function} write @param {Function} fm @returns {number} */
module.exports = function seedStories(write, fm) {
  for (const s of stories) {
    write(
      `backlog/stories/${s.id.toLowerCase()}.md`,
      fm({
        id: s.id,
        type: "story",
        title: s.title,
        status: s.status,
        epicId: s.epicId,
        sprintId: s.sprintId,
        releaseId: s.releaseId,
        startDate: s.startDate,
        dueDate: s.dueDate,
        priority: s.priority,
        created: "2026-05-01",
      }) +
        (storyBodies[s.id] ||
          `## Description\n\n${s.title}\n\n## Acceptance Criteria\n\n- [ ] \n\n## Notes\n\n`),
    );
  }
  return stories.length;
};
