"use strict";

const tasks = [
  // US-001
  {
    id: "TASK-001",
    title: "Implement registration form UI",
    type: "task",
    storyId: "US-001",
    status: "done",
    priority: "high",
    assigneeId: "MBR-001",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-01",
    dueDate: "2026-05-04",
  },
  {
    id: "TASK-002",
    title: "Email verification backend endpoint",
    type: "task",
    storyId: "US-001",
    status: "done",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-03",
    dueDate: "2026-05-06",
  },
  {
    id: "TASK-003",
    title: "Write unit tests for auth service",
    type: "task",
    storyId: "US-001",
    status: "done",
    priority: "medium",
    assigneeId: "MBR-004",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-06",
    dueDate: "2026-05-07",
  },
  // US-002
  {
    id: "TASK-004",
    title: "Integrate Google OAuth2 PKCE flow",
    type: "task",
    storyId: "US-002",
    status: "done",
    priority: "high",
    assigneeId: "MBR-003",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-05",
    dueDate: "2026-05-08",
  },
  {
    id: "TASK-005",
    title: "Integrate Facebook OAuth2 flow",
    type: "task",
    storyId: "US-002",
    status: "done",
    priority: "high",
    assigneeId: "MBR-003",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-07",
    dueDate: "2026-05-10",
  },
  // US-005
  {
    id: "TASK-006",
    title: "Build product listing form",
    type: "task",
    storyId: "US-005",
    status: "done",
    priority: "high",
    assigneeId: "MBR-001",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-03",
    dueDate: "2026-05-08",
  },
  {
    id: "TASK-007",
    title: "Listing approval workflow API",
    type: "task",
    storyId: "US-005",
    status: "done",
    priority: "medium",
    assigneeId: "MBR-002",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-08",
    dueDate: "2026-05-12",
  },
  // US-006
  {
    id: "TASK-008",
    title: "Presigned S3 upload endpoint",
    type: "task",
    storyId: "US-006",
    status: "done",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-06",
    dueDate: "2026-05-09",
  },
  {
    id: "TASK-009",
    title: "Image resize Lambda on upload",
    type: "task",
    storyId: "US-006",
    status: "testing",
    priority: "medium",
    assigneeId: "MBR-005",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-09",
    dueDate: "2026-05-13",
  },
  // US-009
  {
    id: "TASK-010",
    title: "Cart API — add/update/remove items",
    type: "task",
    storyId: "US-009",
    status: "in-progress",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-20",
    dueDate: "2026-05-24",
  },
  {
    id: "TASK-011",
    title: "Cart UI component",
    type: "task",
    storyId: "US-009",
    status: "blocked",
    priority: "high",
    assigneeId: "MBR-001",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-22",
    dueDate: "2026-05-26",
  },
  // US-013
  {
    id: "TASK-012",
    title: "Stripe Elements checkout page",
    type: "task",
    storyId: "US-013",
    status: "todo",
    priority: "high",
    assigneeId: "MBR-001",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-01",
    dueDate: "2026-06-06",
  },
  {
    id: "TASK-013",
    title: "Payment webhook handler",
    type: "task",
    storyId: "US-013",
    status: "todo",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-04",
    dueDate: "2026-06-09",
  },
  {
    id: "TASK-014",
    title: "3DS2 challenge integration",
    type: "task",
    storyId: "US-013",
    status: "blocked",
    priority: "medium",
    assigneeId: "MBR-003",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-07",
    dueDate: "2026-06-10",
  },
  // US-019
  {
    id: "TASK-015",
    title: "Elasticsearch cluster setup on AWS",
    type: "task",
    storyId: "US-019",
    status: "todo",
    priority: "high",
    assigneeId: "MBR-005",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-01",
    dueDate: "2026-06-05",
  },
  {
    id: "TASK-016",
    title: "Product search index mapping",
    type: "task",
    storyId: "US-019",
    status: "todo",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-03",
    dueDate: "2026-06-09",
  },
  {
    id: "TASK-017",
    title: "Search API endpoint and ranking",
    type: "task",
    storyId: "US-019",
    status: "todo",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-06",
    dueDate: "2026-06-12",
  },
  // US-025
  {
    id: "TASK-018",
    title: "ShipStation webhook integration",
    type: "task",
    storyId: "US-025",
    status: "todo",
    priority: "high",
    assigneeId: "MBR-003",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-05",
    dueDate: "2026-06-11",
  },
  {
    id: "TASK-019",
    title: "Order status timeline UI",
    type: "task",
    storyId: "US-025",
    status: "todo",
    priority: "medium",
    assigneeId: "MBR-001",
    sprintId: "SPR-003",
    releaseId: "REL-001",
    startDate: "2026-06-09",
    dueDate: "2026-06-14",
  },
  // Bugs
  {
    id: "BUG-001",
    title: "Registration fails on special chars in password",
    type: "bug",
    storyId: "US-001",
    status: "done",
    priority: "high",
    assigneeId: "MBR-002",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-04",
    dueDate: "2026-05-05",
  },
  {
    id: "BUG-002",
    title: "Google OAuth redirect fails on Safari iOS",
    type: "bug",
    storyId: "US-002",
    status: "testing",
    priority: "high",
    assigneeId: "MBR-004",
    sprintId: "SPR-001",
    releaseId: "REL-001",
    startDate: "2026-05-09",
    dueDate: "2026-05-10",
  },
  {
    id: "BUG-003",
    title: "Product images not loading on slow connections",
    type: "bug",
    storyId: "US-006",
    status: "testing",
    priority: "medium",
    assigneeId: "MBR-004",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-19",
    dueDate: "2026-05-22",
  },
  {
    id: "BUG-004",
    title: "Cart count not updating after item removal",
    type: "bug",
    storyId: "US-010",
    status: "in-progress",
    priority: "high",
    assigneeId: "MBR-001",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-21",
    dueDate: "2026-05-23",
  },
  {
    id: "BUG-005",
    title: "Category page shows incorrect product count",
    type: "bug",
    storyId: "US-007",
    status: "todo",
    priority: "low",
    assigneeId: "MBR-004",
    sprintId: "SPR-002",
    releaseId: "REL-001",
    startDate: "2026-05-25",
    dueDate: "2026-05-27",
  },
];

const taskBodies = {
  "TASK-001": `## Description\n\nBuild the registration form React component with email, password, and confirm-password fields, inline validation, and submit handling.\n\n## Subtasks\n\n- [x] Form component with controlled inputs\n- [x] Client-side validation (email format, password strength)\n- [x] Loading state and error display\n- [x] Connect to /api/auth/register endpoint\n\n## Notes\n\nUse react-hook-form + zod schema for validation.\n`,
  "TASK-002": `## Description\n\nCreate the POST /api/auth/verify-email endpoint that validates the JWT token from the email link and activates the account.\n\n## Subtasks\n\n- [x] Generate signed JWT on registration\n- [x] Send verification email via SendGrid\n- [x] Endpoint validates token and marks account active\n- [x] Token expiry (24h) enforced\n\n## Notes\n\nTokens stored in Redis for single-use invalidation.\n`,
  "TASK-012": `## Description\n\nIntegrate Stripe Elements on the checkout page with card number, expiry, and CVC fields hosted by Stripe.\n\n## Subtasks\n\n- [ ] Install @stripe/react-stripe-js\n- [ ] Create PaymentIntent on backend before rendering form\n- [ ] Handle confirmPayment result and redirect\n- [ ] Error message mapping (card declined, insufficient funds, etc.)\n\n## Notes\n\nUse payment_intent.created and payment_intent.payment_failed webhook events.\n`,
  "TASK-015": `## Description\n\nProvision an Elasticsearch 8.x cluster on AWS OpenSearch Service and configure index settings.\n\n## Subtasks\n\n- [ ] Terraform module for OpenSearch domain\n- [ ] VPC security group rules\n- [ ] Index lifecycle management policy\n- [ ] Kibana dashboard for monitoring\n\n## Notes\n\nm6g.large.search × 2 nodes for staging; m6g.xlarge.search × 3 for production.\n`,
  "BUG-001": `## Description\n\nWhen a user registers with a password containing special characters (e.g. \`!@#$%\`), the server returns a 400 error despite client-side validation passing.\n\n## Steps to Reproduce\n\n1. Navigate to /register\n2. Enter valid email\n3. Enter password: \`P@ssw0rd!\`\n4. Click Register\n5. Server returns 400 Bad Request\n\n## Expected Behavior\n\nRegistration succeeds and verification email is sent.\n\n## Actual Behavior\n\nServer returns: \`{"error": "Invalid password format"}\` even though the password meets requirements.\n\n## Notes\n\nRoot cause: server-side regex was overly restrictive — missing escape for \`!\` and \`@\`.\n`,
  "BUG-003": `## Description\n\nOn slow mobile connections (3G), product images show broken image icons instead of a loading placeholder or progressive fallback.\n\n## Steps to Reproduce\n\n1. Open DevTools → Network throttle to "Slow 3G"\n2. Navigate to any product detail page\n3. Observe image loading behaviour\n\n## Expected Behavior\n\nBlurred low-resolution placeholder shown while full image loads.\n\n## Actual Behavior\n\nBroken image icon displayed until full image loads.\n\n## Notes\n\nImplement BlurHash placeholders stored alongside S3 objects.\n`,
  "BUG-004": `## Description\n\nAfter removing an item from the cart, the cart icon count in the header still shows the old count until the page is refreshed.\n\n## Steps to Reproduce\n\n1. Add 2 items to cart\n2. Open cart drawer\n3. Remove one item\n4. Observe header cart badge — still shows 2\n\n## Expected Behavior\n\nCart badge decrements immediately to 1.\n\n## Actual Behavior\n\nBadge remains at 2; only updates after full page reload.\n\n## Notes\n\nCartContext not triggering re-render — likely a stale closure.\n`,
};

/** @param {Function} write @param {Function} fm @returns {{ tasks: number, bugs: number }} */
module.exports = function seedTasks(write, fm) {
  for (const t of tasks) {
    write(
      `backlog/tasks/${t.id.toLowerCase()}.md`,
      fm({
        id: t.id,
        type: t.type,
        title: t.title,
        status: t.status,
        storyId: t.storyId,
        sprintId: t.sprintId,
        releaseId: t.releaseId,
        startDate: t.startDate,
        dueDate: t.dueDate,
        priority: t.priority,
        assigneeId: t.assigneeId,
        created: "2026-05-01",
      }) +
        (taskBodies[t.id] ||
          (t.type === "bug"
            ? `## Description\n\n${t.title}\n\n## Steps to Reproduce\n\n1. \n2. \n\n## Expected Behavior\n\n\n\n## Actual Behavior\n\n\n\n## Notes\n\n`
            : `## Description\n\n${t.title}\n\n## Subtasks\n\n- [ ] \n\n## Notes\n\n`)),
    );
  }
  return {
    tasks: tasks.filter((t) => t.type === "task").length,
    bugs: tasks.filter((t) => t.type === "bug").length,
  };
};
