import * as vscode from "vscode";
import { parseFrontMatter } from "./specParser";
import type { ItemType } from "./models";

// ---------------------------------------------------------------------------
// Per-field documentation
// ---------------------------------------------------------------------------

const FIELD_DOCS: Record<string, string> = {
  id: [
    "**`id`** — Unique identifier for this item.",
    "",
    "Auto-generated by the extension. **Never change** after creation — other items reference this ID.",
    "",
    "| Type | ID format |",
    "|------|-----------|",
    "| epic | `EPIC-NNN` |",
    "| story | `US-NNN` |",
    "| task | `TASK-NNN` |",
    "| bug | `BUG-NNN` |",
    "| fr | `FR-NNN` |",
    "| nfr | `NFR-NNN` |",
    "| sprint | `SPR-NNN` |",
    "| release | `REL-NNN` |",
    "| adr | `ADR-NNN` |",
    "| arch | `ARCH-NNN` |",
    "| service | `SRV-NNN` |",
    "| data-proc | `DP-NNN` |",
    "| db-table | `TBL-NNN` |",
    "| cicd | `CICD-NNN` |",
    "| auth-spec | `AUTH-NNN` |",
    "| test-plan | `TP-NNN` |",
    "| member | `MBR-NNN` |",
  ].join("\n"),

  type: [
    "**`type`** — Document type. Controls which sidebar view the file appears in, which statuses are valid, and which fields are required.",
    "",
    "| Value | Sidebar view | ID prefix |",
    "|-------|-------------|-----------|",
    "| `epic` | Backlog | `EPIC-NNN` |",
    "| `story` | Backlog | `US-NNN` |",
    "| `task` | Backlog | `TASK-NNN` |",
    "| `bug` | Backlog | `BUG-NNN` |",
    "| `fr` | Requirements | `FR-NNN` |",
    "| `nfr` | Requirements | `NFR-NNN` |",
    "| `sprint` | Sprints & Releases | `SPR-NNN` |",
    "| `release` | Sprints & Releases | `REL-NNN` |",
    "| `adr` | Technical | `ADR-NNN` |",
    "| `arch` | Technical | `ARCH-NNN` |",
    "| `service` | Technical | `SRV-NNN` |",
    "| `data-proc` | Technical | `DP-NNN` |",
    "| `db-table` | Database | `TBL-NNN` |",
    "| `cicd` | Technical | `CICD-NNN` |",
    "| `auth-spec` | Technical | `AUTH-NNN` |",
    "| `test-plan` | Technical | `TP-NNN` |",
    "| `member` | Team | `MBR-NNN` |",
  ].join("\n"),

  title: [
    "**`title`** — Human-readable display name for this item.",
    "",
    "Always enclose in double quotes in the front matter. Shown in the sidebar tree, planning board, and timeline.",
    "",
    "```yaml",
    'title: "My Feature Title"',
    "```",
  ].join("\n"),

  status: [
    "**`status`** — Current lifecycle state. Valid values depend on the document type:",
    "",
    "| Type | Valid statuses |",
    "|------|---------------|",
    "| epic, story, fr, nfr, arch, service, data-proc, cicd, auth-spec, test-plan | `draft` · `active` · `deprecated` |",
    "| task, bug | `todo` · `in-progress` · `testing` · `blocked` · `done` |",
    "| adr | `proposed` · `accepted` · `deprecated` · `superseded` |",
    "| sprint | `planned` · `active` · `done` |",
    "| release | `draft` · `active` · `released` |",
    "| member | `active` · `draft` |",
  ].join("\n"),

  created: [
    "**`created`** — Date this document was created.",
    "",
    "ISO format: `YYYY-MM-DD`. Set automatically when the file is created — do not change.",
    "",
    "```yaml",
    "created: 2026-05-15",
    "```",
  ].join("\n"),

  epicId: [
    "**`epicId`** *(required on stories)* — Reference to the parent epic.",
    "",
    "Links this story to its parent epic in the **Backlog** view. The epic must exist (format: `EPIC-NNN`).",
    "",
    "```yaml",
    "epicId: EPIC-003",
    "```",
    "",
    "**Relationship:** story → epic (many-to-one)",
  ].join("\n"),

  storyId: [
    "**`storyId`** *(required on tasks and bugs)* — Reference to the parent user story.",
    "",
    "Links this task/bug to its parent story in the **Backlog** view. The story must exist (format: `US-NNN`).",
    "",
    "```yaml",
    "storyId: US-005",
    "```",
    "",
    "**Relationship:** task/bug → story (many-to-one)",
  ].join("\n"),

  sprintId: [
    "**`sprintId`** — Sprint this item is assigned to.",
    "",
    "Used on stories, tasks, and bugs. Visible in the **Sprints & Releases** view and the timeline. Format: `SPR-NNN`.",
    "",
    "```yaml",
    "sprintId: SPR-002",
    "```",
    "",
    "**Relationship:** story/task/bug → sprint (many-to-one)",
  ].join("\n"),

  releaseId: [
    "**`releaseId`** — Release this item is assigned to.",
    "",
    "Used on stories, tasks, and bugs. Visible in the **Sprints & Releases** view. Format: `REL-NNN`.",
    "",
    "```yaml",
    "releaseId: REL-001",
    "```",
    "",
    "**Relationship:** story/task/bug → release (many-to-one)",
  ].join("\n"),

  linkedIds: [
    "**`linkedIds`** — Comma-separated IDs of items that implement or relate to this requirement.",
    "",
    "Used on **fr** and **nfr** files. No spaces around commas. Links requirements to the stories and tasks that fulfil them — shown in the **Requirements** view.",
    "",
    "```yaml",
    "linkedIds: US-003,TASK-007,TASK-008",
    "```",
    "",
    "**Relationship:** fr/nfr → stories/tasks (many-to-many via comma list)",
  ].join("\n"),

  dependsOn: [
    "**`dependsOn`** — Comma-separated IDs of items that must be completed before this one.",
    "",
    "Expresses a blocking dependency. No spaces around commas.",
    "",
    "```yaml",
    "dependsOn: TASK-003,TASK-004",
    "```",
    "",
    "**Relationship:** item → blocking items (many-to-many via comma list)",
  ].join("\n"),

  priority: [
    "**`priority`** — Priority level. Used on stories, tasks, bugs, FRs, and NFRs.",
    "",
    "Valid values: `high` · `medium` · `low`",
    "",
    "Shown as a badge in the **Backlog** view and on planning board cards.",
  ].join("\n"),

  assigneeId: [
    "**`assigneeId`** — Team member assigned to this task or bug.",
    "",
    "References a member file in the **Team** view. Format: `MBR-NNN`.",
    "",
    "```yaml",
    "assigneeId: MBR-002",
    "```",
    "",
    "**Relationship:** task/bug → member (many-to-one)",
  ].join("\n"),

  role: [
    "**`role`** *(required on members)* — Role of the team member.",
    "",
    "Free text. Displayed in the **Team** view alongside the member's name.",
    "",
    "Common values: `frontend` · `backend` · `devops` · `design` · `qa` · `pm`",
    "",
    "```yaml",
    "role: backend",
    "```",
  ].join("\n"),

  startDate: [
    "**`startDate`** — Planned start date. ISO format: `YYYY-MM-DD`.",
    "",
    "Used on epics, stories, tasks, bugs, and sprints. Drives the left edge of the bar in the **Timeline** view.",
    "",
    "```yaml",
    "startDate: 2026-05-15",
    "```",
  ].join("\n"),

  dueDate: [
    "**`dueDate`** — Planned completion date. ISO format: `YYYY-MM-DD`.",
    "",
    "Used on epics, stories, tasks, bugs, and sprints. Drives the right edge of the bar in the **Timeline** view.",
    "",
    "```yaml",
    "dueDate: 2026-05-28",
    "```",
  ].join("\n"),

  releaseDate: [
    "**`releaseDate`** — Target release date for a **release** document. ISO format: `YYYY-MM-DD`.",
    "",
    "Shown as the release milestone marker in the **Timeline** view.",
    "",
    "```yaml",
    "releaseDate: 2026-06-30",
    "```",
  ].join("\n"),

  relations: [
    "**`relations`** — Foreign-key relations for a **db-table** document.",
    "",
    "Comma-separated `columnName:TBL-NNN` pairs. Rendered as arrows in the **Database** diagram view. No spaces around commas or colons.",
    "",
    "```yaml",
    "relations: userId:TBL-001,orderId:TBL-002",
    "```",
    "",
    "**Relationship:** db-table column → db-table (FK arrow in Database view)",
  ].join("\n"),

  processType: [
    "**`processType`** *(required on data-proc)* — Execution model of the data process.",
    "",
    "Valid values: `sync` · `async` · `cron`",
    "",
    "- `sync` — executes inline, caller waits for completion",
    "- `async` — executes in the background, caller does not block",
    "- `cron` — scheduled execution on a time interval",
    "",
    "```yaml",
    "processType: async",
    "```",
  ].join("\n"),

  testScope: [
    "**`testScope`** *(required on test-plan)* — Scope of the test plan.",
    "",
    "Valid values: `integration` · `e2e`",
    "",
    "- `integration` — verifies interaction between components/services (no full user-facing flow)",
    "- `e2e` — verifies a complete user-facing flow end-to-end",
    "",
    "```yaml",
    "testScope: e2e",
    "```",
  ].join("\n"),
};

// ---------------------------------------------------------------------------
// Per-type documentation (shown when cursor is on the type value)
// ---------------------------------------------------------------------------

const TYPE_DOCS: Record<ItemType, string> = {
  epic: [
    "## Epic",
    "**View:** Backlog  |  **ID:** `EPIC-NNN`  |  **File:** `.spec/backlog/epics/epic-NNN.md`",
    "",
    "A high-level deliverable that groups related user stories. Represents a significant feature or area of work.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Optional fields:** `startDate`, `dueDate`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Relations:**",
    "- Has many → **stories** (stories reference this via `epicId`)",
    "",
    "**Appears in:** Backlog tree, Board view (swim lanes), Timeline view",
  ].join("\n"),

  story: [
    "## User Story",
    "**View:** Backlog  |  **ID:** `US-NNN`  |  **File:** `.spec/backlog/stories/us-NNN.md`",
    "",
    'A user-facing feature described from the user\'s perspective: *"As a [role], I can [action] so that [benefit]."*',
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`, **`epicId`**",
    "",
    "**Optional fields:** `sprintId`, `releaseId`, `startDate`, `dueDate`, `priority`, `dependsOn`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Relations:**",
    "- Belongs to → **epic** (via `epicId`)",
    "- Has many → **tasks** and **bugs** (they reference this via `storyId`)",
    "- May belong to → **sprint** (via `sprintId`) and **release** (via `releaseId`)",
    "",
    "**Appears in:** Backlog tree, Board view (cards), Timeline view",
  ].join("\n"),

  task: [
    "## Task",
    "**View:** Backlog  |  **ID:** `TASK-NNN`  |  **File:** `.spec/backlog/tasks/task-NNN.md`",
    "",
    "A concrete unit of work that implements part of a user story.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`, **`storyId`**",
    "",
    "**Optional fields:** `sprintId`, `releaseId`, `startDate`, `dueDate`, `priority`, `assigneeId`, `dependsOn`",
    "",
    "**Valid statuses:** `todo` · `in-progress` · `testing` · `blocked` · `done`",
    "",
    "**Relations:**",
    "- Belongs to → **story** (via `storyId`)",
    "- May belong to → **sprint** (via `sprintId`) and **release** (via `releaseId`)",
    "- May be assigned to → **member** (via `assigneeId`)",
    "",
    "**Appears in:** Backlog tree, Board view (cards)",
  ].join("\n"),

  bug: [
    "## Bug",
    "**View:** Backlog  |  **ID:** `BUG-NNN`  |  **File:** `.spec/backlog/tasks/bug-NNN.md`",
    "",
    "A defect linked to a user story. Same schema as a task but with a different prefix and body template.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`, **`storyId`**",
    "",
    "**Optional fields:** `sprintId`, `releaseId`, `startDate`, `dueDate`, `priority`, `assigneeId`, `dependsOn`",
    "",
    "**Valid statuses:** `todo` · `in-progress` · `testing` · `blocked` · `done`",
    "",
    "**Relations:**",
    "- Belongs to → **story** (via `storyId`)",
    "- May belong to → **sprint** (via `sprintId`) and **release** (via `releaseId`)",
    "- May be assigned to → **member** (via `assigneeId`)",
    "",
    "**Appears in:** Backlog tree, Board view (cards with bug icon)",
  ].join("\n"),

  fr: [
    "## Functional Requirement",
    "**View:** Requirements  |  **ID:** `FR-NNN`  |  **File:** `.spec/requirements/fr/fr-NNN.md`",
    "",
    "Describes what the system **shall do** — a capability or behaviour required by stakeholders.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Optional fields:** `linkedIds`, `priority`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Relations:**",
    "- Links to → **stories / tasks** that implement it (via `linkedIds`, comma-separated)",
    "",
    "**Appears in:** Requirements tree",
  ].join("\n"),

  nfr: [
    "## Non-Functional Requirement",
    "**View:** Requirements  |  **ID:** `NFR-NNN`  |  **File:** `.spec/requirements/nfr/nfr-NNN.md`",
    "",
    "Describes **how** the system behaves — quality attributes such as performance, security, scalability, and reliability.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Optional fields:** `linkedIds`, `priority`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Relations:**",
    "- Links to → **stories / tasks** (via `linkedIds`, comma-separated)",
    "",
    "**Appears in:** Requirements tree",
  ].join("\n"),

  sprint: [
    "## Sprint",
    "**View:** Sprints & Releases  |  **ID:** `SPR-NNN`  |  **File:** `.spec/planning/sprints/spr-NNN.md`",
    "",
    "A time-boxed iteration. Defines the goal and duration of a development cycle.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Optional fields:** `startDate`, `dueDate`",
    "",
    "**Valid statuses:** `planned` · `active` · `done`",
    "",
    "**Relations:**",
    "- Referenced by → **stories, tasks, bugs** (they point here via `sprintId`)",
    "",
    "**Appears in:** Sprints & Releases tree, Timeline view",
  ].join("\n"),

  release: [
    "## Release",
    "**View:** Sprints & Releases  |  **ID:** `REL-NNN`  |  **File:** `.spec/planning/releases/rel-NNN.md`",
    "",
    "A versioned deployment milestone containing a set of completed stories.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Optional fields:** `releaseDate`",
    "",
    "**Valid statuses:** `draft` · `active` · `released`",
    "",
    "**Relations:**",
    "- Referenced by → **stories, tasks, bugs** (they point here via `releaseId`)",
    "",
    "**Appears in:** Sprints & Releases tree, Timeline view (milestone marker)",
  ].join("\n"),

  adr: [
    "## Architecture Decision Record (ADR)",
    "**View:** Technical  |  **ID:** `ADR-NNN`  |  **File:** `.spec/technical/adr/adr-NNN.md`",
    "",
    "Documents a significant architectural decision: the context, the decision made, its consequences, and alternatives considered.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Valid statuses:** `proposed` · `accepted` · `deprecated` · `superseded`",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  arch: [
    "## Architecture Doc",
    "**View:** Technical  |  **ID:** `ARCH-NNN`  |  **File:** `.spec/technical/arch/arch-NNN.md`",
    "",
    "High-level architecture documentation: system diagrams, component maps, and interface definitions.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  "service": [
    "## Service",
    "**View:** Technical  |  **ID:** `SRV-NNN`  |  **File:** `.spec/technical/services/srv-NNN.md`",
    "",
    "Detailed specification for a module, service, or subsystem: API contracts, data flows, implementation notes.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  "data-proc": [
    "## Data Process",
    "**View:** Technical  |  **ID:** `DP-NNN`  |  **File:** `.spec/technical/data-processes/dp-NNN.md`",
    "",
    "Documents a data process: ETL pipeline, transformation step, event flow, or any data-in / data-out operation.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`, `processType`",
    "",
    "**`processType`:** `sync` · `async` · `cron`",
    "",
    "**Valid statuses:** `draft` · `active` · `deprecated`",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  "db-table": [
    "## Database Table",
    "**View:** Database  |  **ID:** `TBL-NNN`  |  **File:** `.spec/technical/database/tbl-NNN.md`",
    "",
    "Schema definition for a single database table, including columns and foreign-key relationships.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Optional fields:** `relations`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Relations:**",
    "- Links to → **other tables** via `relations` field (`colName:TBL-NNN` pairs)",
    "",
    "**Appears in:** Database tree, Database diagram view (nodes and FK arrows)",
  ].join("\n"),

  cicd: [
    "## CI/CD Pipeline Doc",
    "**View:** Technical  |  **ID:** `CICD-NNN`  |  **File:** `.spec/technical/cicd/cicd-NNN.md`",
    "",
    "Documents a continuous integration or deployment pipeline: stages, triggers, configuration.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  "auth-spec": [
    "## Auth Specification",
    "**View:** Technical  |  **ID:** `AUTH-NNN`  |  **File:** `.spec/technical/auth/auth-NNN.md`",
    "",
    "Specification for authentication and authorization flows, token handling, and security controls.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Valid statuses:** `draft` · `active` · `done`",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  "test-plan": [
    "## Test Plan",
    "**View:** Technical  |  **ID:** `TP-NNN`  |  **File:** `.spec/technical/test-plans/tp-NNN.md`",
    "",
    "A test plan for a feature or flow, covering integration or e2e scope. Body sections group scenarios into Happy Path, Edge Cases, and Abuse Cases.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`, **`testScope`**",
    "",
    "**`testScope`:** `integration` · `e2e`",
    "",
    "**Optional fields:** `linkedIds`",
    "",
    "**Valid statuses:** `draft` · `active` · `deprecated`",
    "",
    "**Relations:**",
    "- Links to → **stories / epics** it covers (via `linkedIds`, comma-separated)",
    "",
    "**Appears in:** Technical tree",
  ].join("\n"),

  member: [
    "## Team Member",
    "**View:** Team  |  **ID:** `MBR-NNN`  |  **File:** `.spec/team/members/mbr-NNN.md`",
    "",
    "Represents a person on the team. Tasks and bugs can reference members via `assigneeId`.",
    "",
    "**Required fields:** `id`, `type`, `title` (full name), `status`, `created`, **`role`**",
    "",
    "**Valid statuses:** `active` · `draft`",
    "",
    "**Relations:**",
    "- Referenced by → **tasks, bugs** (via `assigneeId`)",
    "",
    "**Appears in:** Team tree",
  ].join("\n"),

  concept: [
    "## Concept Document",
    "**View:** Concept  |  **ID:** `CON-NNN`",
    "",
    "A document in one of the concept sections: History & Problem, Goals, Core Principles, Risks & Obstacles, System Design, or System Implementation.",
    "",
    "**Required fields:** `id`, `type`, `title`, `status`, `created`",
    "",
    "**Valid statuses:** `draft` · `active` · `deprecated`",
    "",
    "**Appears in:** Concept tree",
  ].join("\n"),
};

// ---------------------------------------------------------------------------
// Helper — find key under cursor within a front-matter block
// ---------------------------------------------------------------------------

function getFrontMatterKey(
  document: vscode.TextDocument,
  position: vscode.Position,
): { key: string; value: string } | null {
  const text = document.getText();

  // Only trigger inside the first front-matter block
  const fmMatch = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!fmMatch) {
    return null;
  }

  const fmEnd = fmMatch[0].length;
  const offset = document.offsetAt(position);
  // +4 for the opening "---\n"
  if (offset > fmEnd) {
    return null;
  }

  const line = document.lineAt(position).text;
  const colonIdx = line.indexOf(":");
  if (colonIdx <= 0) {
    return null;
  }

  const key = line.slice(0, colonIdx).trim();
  const value = line
    .slice(colonIdx + 1)
    .trim()
    .replace(/^["']|["']$/g, "");

  // Only hover if cursor is over the key portion (before or on the colon)
  if (position.character > colonIdx) {
    // Allow hovering on a known type value too
    if (key === "type") {
      return { key, value };
    }
    return null;
  }

  return { key, value };
}

// ---------------------------------------------------------------------------
// Hover provider
// ---------------------------------------------------------------------------

export class SpecHoverProvider implements vscode.HoverProvider {
  constructor(
    private readonly getDocType: (filePath: string) => ItemType | undefined,
  ) {}

  provideHover(
    document: vscode.TextDocument,
    position: vscode.Position,
  ): vscode.Hover | null {
    const hit = getFrontMatterKey(document, position);
    if (!hit) {
      return null;
    }

    let mdText: string | undefined;

    if (hit.key === "type") {
      // If cursor is past the colon, show type-specific docs for the value
      const typeValue = hit.value as ItemType;
      mdText = TYPE_DOCS[typeValue] ?? FIELD_DOCS["type"];
    } else {
      mdText = FIELD_DOCS[hit.key];
    }

    if (!mdText) {
      return null;
    }

    return new vscode.Hover(new vscode.MarkdownString(mdText, true));
  }
}

// ---------------------------------------------------------------------------
// Factory helper used in extension.ts
// ---------------------------------------------------------------------------

export function registerHoverProvider(
  context: vscode.ExtensionContext,
  getItems: () => import("./models").SpecItem[],
): void {
  const getDocType = (filePath: string): ItemType | undefined => {
    const item = getItems().find((i) => i.filePath === filePath);
    return item?.data.type;
  };

  context.subscriptions.push(
    vscode.languages.registerHoverProvider(
      { language: "markdown", pattern: "**/.spec/**/*.md" },
      new SpecHoverProvider(getDocType),
    ),
  );
}
